radarr:
  movies:
    base_url: http://radarr:7878
    api_key: !env_var RADARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    quality_profiles:
      - name: Movies-720p
        upgrade:
          allowed: false
        qualities:
          - name: WEBRip-720p
          - name: WEBDL-720p
          - name: Bluray-720p

      - name: Movies-1080p
        upgrade:
          allowed: true
          until_quality: Bluray-1080p
        qualities:
          - name: WEBRip-720p
          - name: WEBDL-720p
          - name: Bluray-720p
          - name: WEBRip-1080p
          - name: WEBDL-1080p
          - name: Bluray-1080p

      - name: Movies-2160p
        upgrade:
          allowed: true
          until_quality: Bluray-2160p
        qualities:
          - name: WEBRip-720p
          - name: WEBDL-720p
          - name: Bluray-720p
          - name: WEBRip-1080p
          - name: WEBDL-1080p
          - name: Bluray-1080p
          - name: WEBRip-2160p
          - name: WEBDL-2160p
          - name: Bluray-2160p

    custom_formats:
      - trash_ids:
          # HDR Formats
          - 493b6d1dbec3c3364c59d7607f7e3405  # HDR
          - caa37d0df9c348912df1fb1d88f9273a  # HDR10Plus Boost
          # Movie Versions
          - 570bc9ebecd92723d2d21500f4be314c  # Remaster
          - eca37840c13c6ef2dd0262b141a5482f  # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319  # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c  # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9  # Vinegar Syndrome
          - e9001909a4c88013a359d0b9920d7bea  # Theatrical Cut
          - 957d0f44b592285f26449575e8b1167e  # Special Edition
          - eecf3a857724171f968a66cb5719e152  # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de  # IMAX Enhanced
          # Unwanted
          - cae4ca30163749b891686f95532519bd  # AV1
          - ed38b889b31be83fda192888e2286d83  # BR-DISK
          - e6886871085226c3da1830830146846c  # Generated Dynamic HDR
          - 90a6f9a284dff5103f6346090e6280c8  # LQ - may need to remove as it includes YTS which I don't mind
          - e204b80c87be9497a8a6eaff48f72905  # LQ (Release Title)
          - b8cd450cbfa689c0259a01d9e29ba3d6  # 3D
          - bfd8eb01832d646a0a89c4deb46f8564  # Upscaled
          - 0a3f082873eb454bde444150b70253cc  # Extras
          # Miscellaneous
          - b6832f586342ef70d9c128d40c07b872  # Bad Dual Groups
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5  # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2  # Obfuscated
          - f537cf427b64c38c8e36298f657e4828  # Scene
          # - 839bea857ed2c0a8e084f3cbdbd65ecb  # x265 (no HDR/DV)  - will need to rescore x265 (HD) if wanting to use this
          - 11cd1db7165d6a7ad9a83bc97b8b1060  # VC-1
          - ae4cfaa9283a4f2150ac3da08e388723  # VP9
          - 182fa1c42a2468f8488e6dcf75a81b81  # Internal
          - c465ccc73923871b3eb1802042331306  # Line/Mic Dubbed
          - 73613461ac2cea99d52c4cd6e177ab82  # HFR
          - e7718d7a3ce595f289bfee26adc178f5  # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4  # Repack2
          - 5caaaa1c08c1742aa4342d8c4cc463f2  # Repack3
          # - 2899d84dc9372de3408e6d8cc18e9666  # x264  - unnecessary as covered by x265 (HD) blocking
          # HQ Release Groups
          - 4d74ac4c4db0b64bff6ce0cffef99bf0  # UHD Bluray Tier 1
          - a58f517a70193f8e578056642178419d  # UHD Bluray Tier 2
          - e71939fae578037e7aed3ee219bbe7c1  # UHD Bluray Tier 3
          - ed27ebfef2f323e964fb1f61391bcb35  # HD Bluray Tier 1
          - c20c8647f2746a1f4c4262b0fbbeeeae  # HD Bluray Tier 2
          - 5608c71bcebba0a5e666223bae8c9227  # HD Bluray Tier 3
          - c20f169ef63c5f40c2def54abaf4438e  # WEB Tier 1
          - 403816d65392c79236dcb6dd591aeda4  # WEB Tier 2
          - af94e0fe497124d1f9ce732069ec8c3b  # WEB Tier 3
          # Streaming Services
          - b3b3a6ac74ecbd56bcdbefa4799fb9df  # AMZN
          - df13ed57843877b21ad969184ab6888f  # ATV
          - 40e9380490e748672c2522eaaeb692f7  # ATVP
          - cc5e51a9e85a6296ceefe097a77f12f4  # BCORE
          - 16622a6911d1ab5d5b8b713d5b0036d4  # CRiT
          - 84272245b2988854bfb76a16e60baea5  # DSNP
          - 509e5f41146e278f9eab1ddaceb34515  # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad  # HMAX
          - 526d445d4c16214309f0fd2b3be18a89  # HULU
          - e0ec9672be6cac914ffad34a6b077209  # IT
          - 6a061313d22e51e0f25b7cd4dc065233  # MAX
          - 2a6039655313bf5dab1e43523b62c374  # MA
          - 170b1d363bd8516fbf3a3eb05d4faff6  # NF
          - c9fd353f8f5f1baf56dc601c4cb29920  # PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd  # PMTP
          - 350e9170619683a55cb9191d0b1ababa  # PLAY
          - 44c2b54d7c81c1a442a8b2cabeaef54f  # ROKU
          - d9058beaae2e147183870304dd526761  # CBC
          - f6ff65b3f4b464a79dcc75950fe20382  # CRAV
        assign_scores_to:
          - name: Movies-720p
          - name: Movies-1080p
          - name: Movies-2160p
      - trash_ids:
          - dc98083864ea246d05a42df0d05f81cc  # x265 (HD)
        assign_scores_to:
          - name: Movies-720p
            score: -10000
          - name: Movies-1080p
            score: -10000
      - trash_ids:
          - b337d6812e06c200ec9a2d3cfa9d20a7  # DV Boost - need a low score to prevent them
          - f700d29429c023a5734505e77daeaea7  # DV (Disk)
          - 923b6abef9b17f937fab56cfcf89e1f1  # DV (w/o HDR fallback)
        assign_scores_to:
          - name: Movies-720p
            score: -10000
          - name: Movies-1080p
            score: -10000
          - name: Movies-2160p
            score: -10000
