sonarr:
  tv:
    base_url: http://sonarr:8989
    api_key: !env_var SONARR_API_KEY

    delete_old_custom_formats: false
    replace_existing_custom_formats: true

    quality_profiles:
      - name: TV-720p
        upgrade:
          allowed: false
        qualities:
          - name: HDTV-720p
          - name: WEBRip-720p
          - name: WEBDL-720p
          - name: Bluray-720p

      - name: TV-1080p
        upgrade:
          allowed: true
          until_quality: Bluray-1080p
        qualities:
          - name: HDTV-720p
          - name: WEBRip-720p
          - name: WEBDL-720p
          - name: Bluray-720p
          - name: HDTV-1080p
          - name: WEBRip-1080p
          - name: WEBDL-1080p
          - name: Bluray-1080p

      - name: TV-2160p
        upgrade:
          allowed: true
          until_quality: Bluray-2160p
        qualities:
          - name: HDTV-720p
          - name: WEBRip-720p
          - name: WEBDL-720p
          - name: Bluray-720p
          - name: HDTV-1080p
          - name: WEBRip-1080p
          - name: WEBDL-1080p
          - name: Bluray-1080p
          - name: WEBRip-2160p
          - name: WEBDL-2160p
          - name: Bluray-2160p

    custom_formats:
      - trash_ids: 
        - e6258996055b9fbab7e9cb2f75819294  # WEB Tier 1
        - 58790d4e2fdcd9733aa7ae68ba2bb503  # WEB Tier 2
        - d84935abd3f8556dcd51d4f27e22d0a6  # WEB Tier 3
        - d0c516558625b04b363fa6c5c2c7cfd4  # WEB Scene
      - assign_scores_to:
        - name: TV-720p
        - name: TV-1080p
        - name: TV-2160p
