services:
  caddy:
    image: caddy:latest
    container_name: infra_proxy_caddy
    network_mode: host
    depends_on:
      - homarr
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /srv/appdata/infra/proxy/caddy/data:/data:rw
      - /srv/appdata/infra/proxy/caddy/config:/config:rw
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped