services:
  caddy:
    image: caddy:latest
    container_name: infra_proxy_caddy
    network_mode: host
    environment:
      - TZ=${TZ}
      - BASIC_AUTH_HASH=${BASIC_AUTH_HASH}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /srv/appdata/infra/proxy/caddy/data:/data:rw
      - /srv/appdata/infra/proxy/caddy/config:/config:rw
    restart: unless-stopped