services:  
  uptime-kuma:
    image: louislam/uptime-kuma:2.0.2
    container_name: infra_monitoring_uptime-kuma
    environment:
      - TZ=${TZ}
    volumes:
      - /srv/appdata/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3001:3001
    restart: unless-stopped