services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: infra_monitoring_dozzle
    environment:
      - TZ=${TZ}
      - DOZZLE_TAILSIZE=300
      - DOZZLE_LEVEL=info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/appdata/infra/monitoring/dozzle/data:/data
    ports:
      - 9999:8080
    restart: unless-stopped
